#lang racket

(define (equal? a b)
  (cond ((and (pair? a) (pair? b) (= (car a) (car b)))
         (if (and (pair? (cdr a)) (pair? (cdr b)))
             (equal? (cdr a) (cdr b))
             #t))
        ((and (not (pair? a)) (not (pair? b)) (= a b)) #t)
        (else #f)))

(define (equal2? p1 p2)
  (cond ((and (null? p1) (null? p2)) #t)
        ((or (null? p1) (null? p2)) #f)
        ((and (pair? p1) (pair? p2))
         (and (equal? (car p1) (car p2))
              (equal? (cdr p1) (cdr p2))))
        ((or (pair? p1) (pair? p2)) #f)
        (else (eq? p1 p2))))

(equal? '(1 2) '(1 2))
(equal? '(1 2 3) '(1 2 3))
(equal? 3 4)
(equal? 4 4)
(equal? 4 '(1 2))

(equal2? '(1 2) '(1 2))
(equal2? '(1 2 3) '(1 2 3))
(equal2? 3 4)
(equal2? 4 4)
(equal2? 4 '(1 2))
